### Get all projects
GET http://localhost:5100/projects
Accept: application/json

### Get project by id
GET http://localhost:5100/projects/626e93ec-f226-49c8-b849-f6536d9a4934
Accept: application/json

### Create a new project
POST http://localhost:5100/projects
Content-Type: application/json
Accept: application/json

{
  "name": "Demo Project",
  "description": "A demo project for testing",
  "status": "New"
}

### Update a project
PUT http://localhost:5100/projects/626e93ec-f226-49c8-b849-f6536d9a4934
Content-Type: application/json
Accept: application/json

{
  "name": "Updated Project Name",
  "description": "Updated description",
  "status": "Active"
}

### Delete a project
DELETE http://localhost:5100/projects/626e93ec-f226-49c8-b849-f6536d9a4934
Accept: application/json




### Get all workitems
GET http://localhost:5100/workitems
Accept: application/json

### Get workitem by id
GET http://localhost:5100/workitems/522e89fd-affd-40db-9664-a3952df56ad2
Accept: application/json

### Create a new workitem
POST http://localhost:5100/workitems
Content-Type: application/json
Accept: application/json

{
  "projectId": "7529b496-853b-4423-a440-cbe304bfdb5b",
  "title": "Demo WorkItem",
  "description": "A demo work item",
  "status": "New"
}

### Update a workitem
PUT http://localhost:5100/workitems/522e89fd-affd-40db-9664-a3952df56ad2
Content-Type: application/json
Accept: application/json

{
  "projectId": "7529b496-853b-4423-a440-cbe304bfdb5b",
  "title": "Updated WorkItem Title",
  "description": "Updated work item description",
  "status": "InProgress"
}

### Delete a workitem
DELETE http://localhost:5100/workitems/522e89fd-affd-40db-9664-a3952df56ad2
Accept: application/json
